# Run docker-compose build
# Run docker-compose up

version: '3.1'

services:

  foglamp:
    container_name: foglamp-gui
    image: nginx
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "8080:80"
      # - "443:443"

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
